apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: spring-music
spec:
  acceptedServiceBindings:
    - name: mysql
      types:
      - mysql
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    - name: BP_LOG_LEVEL
      value: DEBUG
    path: ../..
  ports:
  - name: main
    port: 8080